import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    /**
     * shadcn/ui files are generated by `npx shadcn@latest add` and are not
     * hand-edited — a fix applied here is silently reverted the next time a
     * component is re-added or updated. So the rule is scoped off rather than
     * the file being patched.
     *
     * The one rule this affects: `use-mobile.ts` sets state once inside its
     * mount effect, which is the standard SSR-safe way to read a media query
     * that has no value on the server. React Compiler's lint is conservative
     * here; the pattern is correct and upstream.
     */
    files: ["components/ui/**", "hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
