import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { eq, sql } from "drizzle-orm";
import { db } from "@/lib/db";
import { cleanupChangeOrderFixture as cleanup } from "./cleanup-change-order-fixture";
import { drawSchedule } from "@/lib/db/schema/draws";
import { shareLinks } from "@/lib/db/schema/sharing";
import { saveChangeOrder, readChangeOrder, sendChangeOrder, decideChangeOrder, invoiceChangeOrder, agreedChangeTargets } from "@/lib/change-orders/service";
import { signDocument } from "@/lib/signing/sign";
import { jobMoney } from "@/lib/queries/jobs";
import { resolveShareToken } from "@/lib/queries/share";
import { recordShareView } from "@/lib/documents/operations/record-view";
import { changeOrderSaveSchema } from "@/lib/schemas/change-order";
import { requestContext, submitChangeRequest, listChangeRequests } from "@/lib/change-orders/requests";
import { createInvoice } from "@/lib/documents/operations/create-invoice";
import { updateInvoice } from "@/lib/documents/operations/update-invoice";
import { documentHash } from "@/lib/signing/hash";
import { documentActivity } from "@/lib/queries/document-activity";
import { changeOrderInvoice } from "@/lib/queries/change-orders";

let passed = 0;
function check(name: string, condition = true) { assert.ok(condition, name); console.log(`ok ${++passed}: ${name}`); }
let orgId: string | undefined;
const attribution = { ip: null, userAgent: "change-order-check" };
if (process.argv[2]) {
  await cleanup(process.argv[2]);
  await globalThis.__fsmDbPool?.end();
  console.log('Isolated test organization cleaned up.');
  process.exit(0);
}
try {
  const [org] = await db.execute<{ id: string }>(sql`insert into organizations (name,slug) values ('Change workflow check', ${`co-check-${randomUUID()}`}) returning id`); orgId = org.id;
  const [customer] = await db.execute<{ id: string }>(sql`insert into customers (organization_id,name) values (${org.id},'Test Customer') returning id`);
  const [job] = await db.execute<{ id: string }>(sql`insert into jobs (organization_id,customer_id,name) values (${org.id},${customer.id},'Change workflow check') returning id`);
  const [parent] = await db.execute<{ id: string }>(sql`insert into documents (organization_id,job_id,customer_id,type,status,title) values (${org.id},${job.id},${customer.id},'contract','generated','Original work') returning id`);
  await db.execute(sql`insert into contract_details (document_id,contract_sum_cents) values (${parent.id},100000)`);
  const [original] = await db.execute<{ id: string }>(sql`insert into scope_nodes (organization_id,document_id,node_type,section,description,quantity,sell_price_cents) values (${org.id},${parent.id},'item','labor','Original work',1,100000) returning id`);
  const raw = (price: number, extra = {}) => changeOrderSaveSchema.parse({ id: randomUUID(), parentContractId: parent.id, title: 'Change', summary: 'Add work', scope: [{ id: null, parentIndex: null, nodeType: 'item', section: 'labor', description: 'Adjustment', quantity: 1, unit: null, unitCostCents: null, markupBps: null, sellPriceCents: price, taxable: false, optional: false, position: 0, source: 'typed' }], ...extra });
  await assert.rejects(() => saveChangeOrder(org.id, null, raw(10000))); check('unsigned contract cannot be amended');
  for (const party of ['contractor','customer'] as const) await signDocument({ documentId: parent.id, organizationId: org.id, party, printedName: party, mark: { kind: 'typed' }, consented: true, authMethod: 'account' });
  await db.insert(drawSchedule).values({ jobId: job.id, contractId: parent.id, position: 0, name: 'Final work', amountCents: 100000, gate: 'on_completion' });
  const input = raw(20000);
  const draft = await saveChangeOrder(org.id, null, input);
  check('change saves in current document model', draft.doc.details?.deltaCents === 20000);
  assert.equal((await saveChangeOrder(org.id, null, input)).doc.id, draft.doc.id); check('create retry reuses its id');
  await assert.rejects(() => readChangeOrder(draft.doc.id, randomUUID())); check('another organization cannot read it');
  const link = await sendChangeOrder(org.id, draft.doc.id, { revision: draft.revision, printedName: 'Contractor', consented: true }, attribution);
  check('shared customer view resolves', (await resolveShareToken(link.token))?.kind === 'change_order');
  await recordShareView(link.token); check('view keeps legal sent state', (await readChangeOrder(draft.doc.id, org.id)).doc.status === 'sent');
  const activity = await documentActivity(draft.doc.id);
  check('the send is recorded as a link to copy', activity.sends.length === 1 && activity.sends[0].channel === 'link');
  check('the open is on its story', activity.visits.length === 1 && activity.url !== null);
  await assert.rejects(() => saveChangeOrder(org.id, null, { ...input, revision: draft.revision })); check('sent version cannot be silently rewritten');
  const sent = await readChangeOrder(draft.doc.id, org.id);
  await assert.rejects(() => decideChangeOrder(link.token, { hash: '0'.repeat(64), decision: 'approve', printedName: 'Customer', consented: true }, attribution)); check('stale customer content is refused');
  await assert.rejects(() => decideChangeOrder(link.token, { hash: sent.hash, decision: 'approve', printedName: 'Customer', consented: false }, attribution)); check('consent is required');
  const decision = { hash: sent.hash, decision: 'approve' as const, printedName: 'Customer', consented: true };
  await Promise.all([decideChangeOrder(link.token, decision, attribution), decideChangeOrder(link.token, decision, attribution)]);
  const approved = await readChangeOrder(draft.doc.id, org.id);
  check('duplicate approval signs once', approved.doc.signatures.length === 2 && approved.doc.status === 'approved');
  check('approval freezes content and preserves signature hash', !!approved.doc.frozenAt && approved.doc.signatures.every(s => s.documentHash === documentHash(approved.doc)));
  check('job total includes adjustment once', (await jobMoney([job.id])).get(job.id)?.totalCents === 120000);
  check('next draw updated once', (await db.select().from(drawSchedule).where(eq(drawSchedule.jobId,job.id)))[0].amountCents === 120000);
  check('agreed scope includes extra work', (await agreedChangeTargets(parent.id, org.id)).length === 2);
  const second = await saveChangeOrder(org.id, null, raw(5000, { billingMode: 'supplemental' }));
  await assert.rejects(() => createInvoice({ organizationId: org.id, input: { jobId: job.id, sourceChangeOrderId: second.doc.id, type: 'draw', amountDueCents: 5000, issue: false } })); check('unapproved change cannot be invoice source');
  const secondLink = await sendChangeOrder(org.id, second.doc.id, { revision: second.revision, printedName: 'Contractor', consented: true }, attribution);
  const secondSent = await readChangeOrder(second.doc.id, org.id);
  await decideChangeOrder(secondLink.token, { ...decision, hash: secondSent.hash }, attribution);
  const [invoiceA, invoiceB] = await Promise.all([invoiceChangeOrder(org.id, second.doc.id), invoiceChangeOrder(org.id, second.doc.id)]);
  check('supplemental invoice creation is retry safe', invoiceA.id === invoiceB.id);
  check('the change order page finds its invoice', (await changeOrderInvoice(second.doc.id, org.id))?.id === invoiceA.id);
  check('...and no other business can', (await changeOrderInvoice(second.doc.id, randomUUID())) === null);
  const decline = await saveChangeOrder(org.id, null, raw(7000));
  const declineLink = await sendChangeOrder(org.id, decline.doc.id, { revision: decline.revision, printedName: 'Contractor', consented: true }, attribution);
  await decideChangeOrder(declineLink.token, { ...decision, hash: (await readChangeOrder(decline.doc.id, org.id)).hash, decision: 'decline' }, attribution);
  check('decline leaves totals untouched', (await jobMoney([job.id])).get(job.id)?.totalCents === 125000);
  await db.update(shareLinks).set({ expiresAt: new Date(0) }).where(eq(shareLinks.token, declineLink.token));
  await assert.rejects(() => decideChangeOrder(declineLink.token, decision, attribution)); check('expired links refused');
  check('existing document link can request changes', (await requestContext(link.token)).id === parent.id);
  const requestId = randomUUID();
  await submitChangeRequest(link.token, requestId, 'Please add an outlet', []);
  await submitChangeRequest(link.token, requestId, 'Please add an outlet', []);
  check('customer request saved once', (await listChangeRequests(job.id, org.id)).length === 1);
  const requested = await saveChangeOrder(org.id, null, raw(8000, { requestId }));
  check('request connects to priced draft', (await listChangeRequests(job.id, org.id))[0].changeOrderId === requested.doc.id);
  const deductionInput = raw(-100000);
  const allowanceInput = raw(5000); allowanceInput.scope[0].nodeType = 'allowance'; allowanceInput.scope[0].description = 'Fixture allowance';
  const allowance = await saveChangeOrder(org.id, null, allowanceInput);
  const allowanceLink = await sendChangeOrder(org.id, allowance.doc.id, { revision: allowance.revision, printedName: 'Contractor', consented: true }, attribution);
  await decideChangeOrder(allowanceLink.token, { ...decision, hash: (await readChangeOrder(allowance.doc.id, org.id)).hash }, attribution);
  const allowanceTarget = (await agreedChangeTargets(parent.id, org.id)).find(n => n.allowance)!;
  const settlementInput = raw(1500); settlementInput.scope[0].referencesNodeId = allowanceTarget.id; settlementInput.scope[0].referenceKind = 'settles';
  const settlement = await saveChangeOrder(org.id, null, settlementInput);
  const staleRemovalInput = raw(-5000); staleRemovalInput.scope[0].referencesNodeId = allowanceTarget.id; staleRemovalInput.scope[0].referenceKind = 'deletes';
  const staleRemoval = await saveChangeOrder(org.id, null, staleRemovalInput);
  const staleRemovalLink = await sendChangeOrder(org.id, staleRemoval.doc.id, { revision: staleRemoval.revision, printedName: 'Contractor', consented: true }, attribution);
  const settlementLink = await sendChangeOrder(org.id, settlement.doc.id, { revision: settlement.revision, printedName: 'Contractor', consented: true }, attribution);
  await decideChangeOrder(settlementLink.token, { ...decision, hash: (await readChangeOrder(settlement.doc.id, org.id)).hash }, attribution);
  check('allowance settlement updates agreed work without an extra scope line', (await agreedChangeTargets(parent.id, org.id)).find(n => n.id === allowanceTarget.id)?.amountCents === 6500);
  check('settled allowance is no longer offered for settlement', !(await agreedChangeTargets(parent.id, org.id)).find(n => n.id === allowanceTarget.id)?.allowance);
  const staleRemovalSent = await readChangeOrder(staleRemoval.doc.id, org.id);
  await assert.rejects(() => decideChangeOrder(staleRemovalLink.token, { ...decision, hash: staleRemovalSent.hash }, attribution)); check('removal cannot credit an obsolete allowance value');
  deductionInput.scope[0].referencesNodeId = original.id; deductionInput.scope[0].referenceKind = 'deletes';
  const deduction = await saveChangeOrder(org.id, null, deductionInput);
  const deductionLink = await sendChangeOrder(org.id, deduction.doc.id, { revision: deduction.revision, printedName: 'Contractor', consented: true }, attribution);
  await decideChangeOrder(deductionLink.token, { ...decision, hash: (await readChangeOrder(deduction.doc.id, org.id)).hash }, attribution);
  check('approved removal changes current scope', !(await agreedChangeTargets(parent.id, org.id)).some(n => n.id === original.id));
  check('deduction changes agreement', (await jobMoney([job.id])).get(job.id)?.totalCents === 31500);
  const billA = await createInvoice({ organizationId: org.id, input: { jobId: job.id, type: 'draw', amountDueCents: 20000, issue: false } });
  const billB = await createInvoice({ organizationId: org.id, input: { jobId: job.id, type: 'draw', amountDueCents: 20000, issue: false } });
  await updateInvoice({ organizationId: org.id, invoiceId: billA.id, input: { issue: true } });
  await assert.rejects(() => updateInvoice({ organizationId: org.id, invoiceId: billB.id, input: { issue: true } })); check('issuing a stale draft rechecks the remaining agreement');
  const excessive = await saveChangeOrder(org.id, null, raw(-20000));
  await assert.rejects(() => sendChangeOrder(org.id, excessive.doc.id, { revision: excessive.revision, printedName: 'Contractor', consented: true }, attribution)); check('deduction below previously billed amount is refused');
  const pendingFinal = await saveChangeOrder(org.id, null, raw(1000));
  const pendingFinalLink = await sendChangeOrder(org.id, pendingFinal.doc.id, { revision: pendingFinal.revision, printedName: 'Contractor', consented: true }, attribution);
  await createInvoice({ organizationId: org.id, input: { jobId: job.id, type: 'final_balance', amountDueCents: 11500, issue: true } });
  const pendingFinalSent = await readChangeOrder(pendingFinal.doc.id, org.id);
  await assert.rejects(() => decideChangeOrder(pendingFinalLink.token, { ...decision, hash: pendingFinalSent.hash }, attribution)); check('final billing between send and approval requires a revised billing choice');
  console.log(`${passed} change-order checks passed.`);
} finally {
  if (orgId) await cleanup(orgId);
  await globalThis.__fsmDbPool?.end();
}
